name: eco_guia
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  fl_chart: ^0.69.0

  flutter:
    sdk: flutter
  shared_preferences: ^2.0.15
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.7
  uuid: ^3.0.4
  path: ^1.8.0
  sqflite: ^2.0.0+4
  sqflite_common_ffi: ^2.0.0
  sqflite_common_ffi_web: ^0.4.5+3
  provider: ^6.0.0
  geolocator: ^9.0.0
  geocoding: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-Regular.ttf

  assets:
    - assets/plastico.png
    - assets/vidro.png
    - assets/papel.png
    - assets/metal.png
    - assets/profile.png

    - assets/coffee_cup.png
    - assets/can.png
    - assets/banana.png
    - assets/plastic-bag.png
    - assets/phone.png

    - assets/card1.png
    - assets/card2.png
    - assets/cardlearn1.png
    - assets/cardlearn2.png

    - assets/nuvem.png
    - assets/bags.png
    - assets/trofeu.png

    - assets/scan_mockup.png
    - assets/logo.svg
